ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 251, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 251, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 251, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 251, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 251, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
ERROR:root:Caught an error
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-06 16:02:14,011
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 264, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-06 21:24:00,057
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:24:39,877
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:24:57,160
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:25:04,472
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:25:21,655
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:25:34,301
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:25:49,427
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:33:49,773
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:34:10,527
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:35:07,282
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:35:22,034
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:36:03,327
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:36:14,001
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:36:26,885
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:36:37,787
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:38:24,014
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 261, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-06 21:39:32,643
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 261, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-06 21:44:56,154
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:47:34,464
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:48:29,529
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:48:34,955
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 282, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-06 21:50:00,302
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 267, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-08 11:40:32,067
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 289, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:40:33,890
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 289, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:40:38,958
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 289, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:40:41,006
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 289, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:45:55,166
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 287, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:46:06,184
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 287, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 11:46:10,886
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 287, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 12:30:51,863
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 287, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 12:34:47,989
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 274, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 12:36:12,342
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 274, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-08 13:56:27,778
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 287, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 10:39:01,502
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 579, in short_gas
    house(11,18,'l',hnum)
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 531, in house
    group('house_l,x')
TypeError: group() missing 1 required positional argument: 'figure'
2021-12-10 10:42:15,554
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 569, in short_gas
    if dir.lower() == 'n':
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-10 11:02:26,721
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 67, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-10 11:02:26,722
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 283, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-10 11:02:54,782
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 67, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-10 11:02:54,783
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 283, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-10 11:59:01,120
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:02,131
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:02,822
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,029
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,193
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,342
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,503
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,648
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-10 11:59:03,839
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 277, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 08:47:52,450
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 292, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 10:36:45,396
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 292, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 10:41:19,954
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 313, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-13 11:32:50,213
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 292, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 12:28:38,889
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 603, in short_gas
    if dir.lower() == 'n':
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-13 12:32:33,356
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 603, in short_gas
    if dir.lower() == 'n':
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-13 13:31:01,118
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 292, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 13:50:17,702
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 292, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 14:19:53,330
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 305, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 14:19:54,747
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 305, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-13 14:19:55,612
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 305, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-14 22:48:08,623
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 83, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-14 22:48:08,654
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 330, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-15 08:54:41,974
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 309, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-15 09:17:34,997
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 627, in short_gas
    if dir.lower() == 'n':
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-15 13:17:13,572
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 670, in long_gas
    hlabel('NRE',27,7)
TypeError: hlabel() missing 1 required positional argument: 'size'
2021-12-15 14:29:15,970
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 634, in short_gas
    if dir.lower() == 'n':
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-15 14:29:18,196
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 309, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-15 15:19:08,677
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 345, in ped
    graph,(x-0.4,y-0.4), (x+0.4,y+0.4), line_color='black',fill_color='white',line_width=1
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2021-12-15 15:19:08,678
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 261, in pole
    TK.addtag_withtag('pole',p)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel.!frame.!frame.!frame2.!canvas addtag pole withtag tagOrId"
2021-12-15 15:19:08,681
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 337, in item_stamp
    sg.Graph.draw_image(graph,location=(x-0.75,y-0.75),data=convert_to_bytes('Drilling.bmp'))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2021-12-15 15:19:08,681
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 281, in transformer
    txr = graph.draw_rectangle((x - 0.5, y - 0.5), (x + 0.5, y + 0.5), line_color="black")
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2021-12-15 15:19:08,682
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 337, in item_stamp
    sg.Graph.draw_image(graph,location=(x-0.75,y-0.75),data=convert_to_bytes('Drilling.bmp'))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2021-12-15 22:24:39,616
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1209, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-16 09:03:10,168
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 309, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-16 09:03:33,343
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 309, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-16 21:24:41,611
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 315, in hlabelm
    v2 = graph.draw_text(vlbl, (x, y), font="Arial 3 normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-16 21:32:49,528
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 80, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-16 21:32:49,549
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 315, in hlabelm
    )
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-16 22:23:24,818
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 344, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-17 09:21:06,640
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 338, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-17 12:26:46,349
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 361, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-20 12:55:56,926
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-20 12:55:57,205
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-20 12:55:57,475
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-20 12:55:58,591
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-20 12:55:59,556
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-20 13:06:31,715
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 714, in read_from_template
    draw_street(flist[1], landbase)
IndexError: list index out of range
2021-12-21 09:02:44,597
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 81, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-21 09:02:44,629
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 348, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-21 09:21:57,195
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:21:58,373
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:21:59,836
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:22:02,494
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:22:04,988
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:24:48,573
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 357, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 09:26:57,471
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1330, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 09:27:18,828
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 10:39:42,549
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 720, in read_from_template
    edge_type = lb_strlist[1].strip()
IndexError: list index out of range
2021-12-21 10:39:47,548
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 10:39:56,726
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 342, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-21 10:40:00,717
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 720, in read_from_template
    edge_type = lb_strlist[1].strip()
IndexError: list index out of range
2021-12-21 16:33:11,604
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:14,385
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:14,656
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:14,832
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:19,949
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:20,113
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:20,322
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:20,483
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:33:20,877
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1335, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-21 16:56:37,550
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 384, in ped
    TK.add_tag_with_tag('ped',pedsq)
AttributeError: 'Canvas' object has no attribute 'add_tag_with_tag'
2021-12-21 16:56:41,778
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 384, in ped
    TK.add_tag_with_tag('ped',pedsq)
AttributeError: 'Canvas' object has no attribute 'add_tag_with_tag'
2021-12-21 16:58:31,844
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 384, in ped
    TK.add_tag_withtag('ped',pedsq)
AttributeError: 'Canvas' object has no attribute 'add_tag_withtag'
2021-12-22 21:56:04,395
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 1442, in <module>
    graph.relocate_figure(item,x,y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5611, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2021-12-22 22:13:26,434
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 81, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-22 22:13:26,435
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 389, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-22 23:08:04,390
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-22 23:08:06,272
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-23 10:54:08,274
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-23 11:15:06,726
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 389, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-23 17:10:37,858
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-23 17:10:38,514
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-23 21:13:20,243
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-23 21:33:51,934
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 81, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-23 21:33:51,934
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 389, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-23 21:36:47,917
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-23 21:44:17,357
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 81, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-23 21:44:17,357
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 389, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-23 21:48:55,207
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 381, in vlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-23 21:50:10,127
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 81, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-23 21:50:10,127
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 372, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-24 11:15:48,029
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-24 11:15:49,147
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-26 09:20:43,036
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 366, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-29 20:42:02,401
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:05,928
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:07,788
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:08,340
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:08,893
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:09,589
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:10,940
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:11,539
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:11,898
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:15,300
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:15,650
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:19,782
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:20,254
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:42:20,585
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:43:14,386
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:43:15,556
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:43:15,901
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:43:16,910
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:43:27,794
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:43:28,785
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 20:44:06,455
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 114, in show_grid
    TK.addtag_withtag('grid',grid)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2720, in addtag_withtag
    self.addtag(newtag, 'withtag', tagOrId)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2687, in addtag
    self.tk.call((self._w, 'addtag') + args)
_tkinter.TclError: wrong # args: should be ".!toplevel2.!frame.!frame2.!frame2.!canvas addtag grid withtag tagOrId"
2021-12-29 21:00:13,161
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 357, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'upper'
2021-12-29 22:18:34,518
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 81, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-29 22:18:34,519
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 380, in vlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal", angle=90
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-30 11:40:25,950
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 823, in read_from_template
    if flist[2]:
IndexError: list index out of range
2021-12-30 11:41:20,487
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 822, in read_from_template
    landbase = set_landbase(dir,edge_type)
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 507, in set_landbase
    vlabel(f'W{edge_type}',swvcurbx - 1,swvcurby2 -1)
TypeError: vlabel() missing 1 required positional argument: 'size'
2021-12-30 12:28:33,544
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 823, in read_from_template
    if flist[2]:
IndexError: list index out of range
2021-12-30 12:44:00,058
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 81, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2021-12-30 12:44:00,060
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 363, in hlabelm
    sg.Graph.draw_text(graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal")
AttributeError: 'NoneType' object has no attribute 'lower'
2021-12-30 21:31:07,389
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 826, in read_from_template
    if flist[2]:
IndexError: list index out of range
2021-12-30 21:32:45,022
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 826, in read_from_template
    if flist[2] is not None:
IndexError: list index out of range
2021-12-30 21:35:14,091
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 826, in read_from_template
    if flist[2] is not None:
IndexError: list index out of range
2021-12-30 23:13:04,635
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 317, in arc
    TK.itemconfig(id,width=2,dash= (10,5))
UnboundLocalError: local variable 'id' referenced before assignment
2022-01-05 21:05:17,410
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 384, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold")
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-02 12:06:18,682
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 395, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold")
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-02 12:06:20,838
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 395, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold")
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-02 12:06:55,257
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawl.py", line 395, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold")
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-04 13:45:42,916
2022-03-04 13:45:42,947
2022-03-04 13:47:24,243
2022-03-04 13:47:24,243
2022-03-04 13:48:29,894
2022-03-04 13:48:29,894
2022-03-04 13:48:30,939
Traceback (most recent call last):
  File "C:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 527, in ped
    (x - 0.4, y - 0.4),
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2022-03-04 13:48:45,932
Traceback (most recent call last):
  File "C:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 479, in hlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold"
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-04 13:48:46,685
Traceback (most recent call last):
  File "C:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 479, in hlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold"
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-04 13:48:46,845
Traceback (most recent call last):
  File "C:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 479, in hlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold"
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-04 13:48:47,646
Traceback (most recent call last):
  File "C:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 479, in hlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold"
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-04 13:48:48,731
Traceback (most recent call last):
  File "C:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 479, in hlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold"
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-04 15:47:54,100
2022-03-04 15:47:54,100
2022-03-04 15:51:07,956
2022-03-04 15:51:07,956
2022-03-07 09:17:42,027
2022-03-07 09:17:42,027
2022-03-07 09:22:23,076
2022-03-07 09:22:23,076
2022-03-07 09:22:32,776
2022-03-07 09:22:32,776
2022-03-07 09:27:30,482
2022-03-07 09:27:30,482
2022-03-07 09:27:41,167
2022-03-07 09:27:41,167
2022-03-07 09:28:04,970
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 528, in hlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold"
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-07 16:29:17,266
2022-03-07 16:29:17,297
2022-03-07 16:29:18,389
2022-03-07 16:29:18,389
2022-03-07 16:29:36,002
2022-03-07 16:29:36,002
2022-03-07 16:33:23,929
2022-03-07 16:33:23,929
2022-03-07 16:35:36,414
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 2275, in <module>
    graph.relocate_figure(item, x, y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5956, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2022-03-07 16:36:12,498
2022-03-07 16:36:12,498
2022-03-07 16:36:19,949
2022-03-07 16:36:19,949
2022-03-07 16:36:29,611
2022-03-07 16:36:29,611
2022-03-07 16:36:40,194
2022-03-07 16:36:40,194
2022-03-07 16:38:07,701
2022-03-07 16:38:07,701
2022-03-07 16:38:16,044
2022-03-07 16:38:16,044
2022-03-07 16:38:52,394
2022-03-07 16:38:52,394
2022-03-07 16:39:19,966
2022-03-07 16:39:19,966
2022-03-07 16:53:47,484
2022-03-07 16:53:47,484
2022-03-07 16:53:48,425
2022-03-07 16:53:48,425
2022-03-07 16:56:49,154
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 1169, in load_sketch_template
    with open(f"{filename}.pkl", "rb") as pk:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Cr/Locatedraw/Locate-draw/95 magnum rd.pkl.pkl'
2022-03-07 16:57:22,262
2022-03-07 16:57:22,262
2022-03-07 17:26:23,909
2022-03-07 17:26:23,909
2022-03-08 10:08:08,650
2022-03-08 10:08:08,666
2022-03-08 10:08:10,212
2022-03-08 10:08:10,212
2022-03-08 10:09:21,755
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 2271, in <module>
    graph.relocate_figure(item, x, y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5956, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
2022-03-08 10:13:50,442
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 148, in convert_measurement
    if len(meas) == 1:
TypeError: object of type 'NoneType' has no len()
2022-03-08 10:13:50,443
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 532, in hlabelm
    graph, msg.lower(), (x, y), font="Arial " + str(size) + " normal"
AttributeError: 'NoneType' object has no attribute 'lower'
2022-03-08 10:15:17,501
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 523, in hlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold"
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-08 10:17:51,692
2022-03-08 10:17:51,692
2022-03-08 10:18:04,458
2022-03-08 10:18:04,458
2022-03-08 10:18:15,525
2022-03-08 10:18:15,525
2022-03-08 11:22:40,927
2022-03-08 11:22:40,927
2022-03-08 11:22:50,455
2022-03-08 11:22:50,455
2022-03-08 11:26:13,213
2022-03-08 11:26:13,213
2022-03-08 11:29:41,789
2022-03-08 11:29:41,789
2022-03-08 11:31:41,507
Traceback (most recent call last):
  File "c:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 523, in hlabel
    graph, msg.upper(), (x, y), font="Arial " + str(size) + " bold"
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-08 11:33:25,768
2022-03-08 11:33:25,768
2022-03-08 17:39:39,640
2022-03-08 17:39:39,702
2022-03-22 14:35:20,727
2022-03-22 14:35:20,727
2022-03-22 14:38:49,879
2022-03-22 14:38:49,879
2022-03-22 14:38:56,476
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 09:57:13,943
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 1168, in load_sketch_template
    with open(f"{filename}.pkl", "rb") as pk:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Cr/Locatedraw/Locate-draw/wbltobl.pkl.pkl'
2022-03-24 09:58:02,490
2022-03-24 09:58:02,490
2022-03-24 10:01:31,458
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 10:02:17,212
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 10:02:18,289
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 10:02:19,615
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 10:02:25,075
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 10:02:37,414
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 10:02:42,984
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 10:02:43,592
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 10:02:45,651
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 10:02:50,160
2022-03-24 10:02:50,175
2022-03-24 10:02:50,175
2022-03-24 10:02:50,191
2022-03-24 10:02:50,191
2022-03-24 10:02:50,222
2022-03-24 10:02:50,222
2022-03-24 10:02:50,284
2022-03-24 10:02:50,300
2022-03-24 10:02:50,316
2022-03-24 10:02:50,331
2022-03-24 10:02:50,331
2022-03-24 10:02:50,347
2022-03-24 10:02:50,347
2022-03-24 10:02:50,347
2022-03-24 10:02:50,362
2022-03-24 10:02:50,378
2022-03-24 10:02:50,440
2022-03-24 10:02:50,456
2022-03-24 10:02:50,472
2022-03-24 10:02:50,472
2022-03-24 10:02:50,487
2022-03-24 10:02:50,487
2022-03-24 10:02:50,487
2022-03-24 10:02:50,487
2022-03-24 10:02:50,503
2022-03-24 10:02:50,503
2022-03-24 10:02:50,534
2022-03-24 10:02:50,550
2022-03-24 10:02:50,581
2022-03-24 10:02:50,596
2022-03-24 10:02:50,612
2022-03-24 10:02:50,612
2022-03-24 10:02:50,674
2022-03-24 10:02:50,690
2022-03-24 10:02:50,690
2022-03-24 10:02:50,690
2022-03-24 10:02:50,721
2022-03-24 10:02:50,737
2022-03-24 10:02:50,752
2022-03-24 10:02:50,784
2022-03-24 10:02:50,799
2022-03-24 10:02:50,799
2022-03-24 10:02:50,830
2022-03-24 10:02:50,846
2022-03-24 10:02:50,877
2022-03-24 10:02:50,893
2022-03-24 10:04:09,486
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 1168, in load_sketch_template
    with open(f"{filename}.pkl", "rb") as pk:
FileNotFoundError: [Errno 2] No such file or directory: 'None.pkl'
2022-03-24 10:10:07,028
2022-03-24 10:10:07,028
2022-03-24 10:14:57,904
2022-03-24 10:14:57,904
2022-03-24 10:15:34,860
2022-03-24 10:15:34,860
2022-03-24 10:25:16,559
2022-03-24 10:25:16,559
2022-03-24 10:31:44,228
2022-03-24 10:31:44,228
2022-03-24 10:49:41,007
2022-03-24 10:49:41,007
2022-03-24 10:57:41,800
2022-03-24 10:57:41,800
2022-03-24 15:48:03,072
2022-03-24 15:48:03,072
2022-03-24 15:50:04,378
2022-03-24 15:50:04,378
2022-03-24 15:50:20,833
2022-03-24 15:50:20,833
2022-03-24 15:50:31,356
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-03-24 15:50:35,767
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-05-04 08:26:35,472
2022-05-04 08:26:35,488
2022-05-04 08:27:59,243
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 547, in vlabel
    graph, msg.upper(), (x, y), font=fontstr,angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2022-05-04 08:27:59,883
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 547, in vlabel
    graph, msg.upper(), (x, y), font=fontstr,angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2022-05-04 08:28:00,195
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 547, in vlabel
    graph, msg.upper(), (x, y), font=fontstr,angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2022-05-04 08:28:00,413
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 547, in vlabel
    graph, msg.upper(), (x, y), font=fontstr,angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2022-05-04 08:28:00,600
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 547, in vlabel
    graph, msg.upper(), (x, y), font=fontstr,angle=90
AttributeError: 'NoneType' object has no attribute 'upper'
2022-05-04 08:28:40,119
2022-05-04 08:28:40,119
2022-05-04 08:28:59,666
2022-05-04 08:28:59,666
2022-05-04 08:29:03,954
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 525, in hlabel
    graph, msg.upper(), (x, y), font=fontstr
AttributeError: 'NoneType' object has no attribute 'upper'
2022-05-05 09:16:39,989
2022-05-05 09:16:40,020
2022-05-05 09:18:10,976
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 529, in hlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font=fontstr)
AttributeError: 'NoneType' object has no attribute 'upper'
2022-05-05 09:19:23,143
2022-05-05 09:19:23,143
2022-05-05 09:23:09,464
2022-05-05 09:23:09,464
2022-05-05 09:26:41,565
2022-05-05 09:26:41,565
2022-05-05 09:27:04,852
2022-05-05 09:27:04,852
2022-05-05 09:27:43,943
2022-05-05 09:27:43,943
2022-05-05 09:28:42,164
2022-05-05 09:28:42,164
2022-05-05 09:31:33,349
2022-05-05 09:31:33,349
2022-05-05 09:31:44,529
2022-05-05 09:31:44,529
2022-05-05 09:32:13,190
2022-05-05 09:32:13,190
2022-05-05 09:32:28,098
2022-05-05 09:32:28,098
2022-05-05 09:34:58,849
2022-05-05 09:34:58,850
2022-05-05 09:45:54,631
2022-05-05 09:45:54,631
2022-05-05 09:46:56,115
2022-05-05 09:46:56,115
2022-05-05 09:53:13,311
Traceback (most recent call last):
  File "C:\Users\Cr\Locatedraw\Locate-draw\ezdrawlnew.py", line 549, in vlabel
    sg.Graph.draw_text(graph, msg.upper(), (x, y), font=fontstr, angle=90)
AttributeError: 'NoneType' object has no attribute 'upper'
2022-05-05 10:21:28,075
2022-05-05 10:21:28,075
2022-05-05 10:29:25,690
2022-05-05 10:29:25,690
2022-05-05 10:33:42,576
2022-05-05 10:33:42,576
2022-05-05 10:34:24,656
2022-05-05 10:34:24,657
2022-05-05 10:34:24,657
2022-05-05 10:34:24,657
2022-05-05 10:34:24,657
2022-05-05 10:51:15,764
2022-05-05 10:51:15,764
2022-05-05 10:51:15,764
2022-05-05 10:51:15,764
2022-05-05 10:51:15,764
2022-05-05 11:03:12,940
2022-05-05 11:03:12,940
2022-05-05 11:03:48,046
2022-05-05 11:03:48,046
2022-05-05 11:03:48,959
2022-05-05 11:03:48,959
2022-05-05 11:08:57,832
Traceback (most recent call last):
  File "c:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 569, in item_stamp
    graph, location=(x - 0.75, y - 0.75), data=convert_to_bytes("Drilling.bmp")
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2022-05-05 11:09:07,611
2022-05-05 11:09:07,611
2022-05-05 11:12:42,071
Traceback (most recent call last):
  File "c:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 569, in item_stamp
    graph, location=(x - 0.75, y - 0.75), data=convert_to_bytes("Drilling.bmp")
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2022-05-05 11:15:48,573
2022-05-05 11:15:48,573
2022-05-05 12:28:58,747
2022-05-05 12:28:58,747
2022-05-05 12:29:00,406
2022-05-05 12:29:00,406
2022-05-05 12:44:36,134
Traceback (most recent call last):
  File "c:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 569, in item_stamp
    graph, location=(x - 0.75, y - 0.75), data=convert_to_bytes("Drilling.bmp")
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2022-05-05 13:06:29,196
Traceback (most recent call last):
  File "c:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 569, in item_stamp
    graph, location=(x - 0.75, y - 0.75), data=convert_to_bytes("Drilling.bmp")
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2022-05-05 13:17:42,679
Traceback (most recent call last):
  File "c:/Users/Cr/Locatedraw/Locate-draw/ezdrawlnew.py", line 2313, in <module>
    graph.relocate_figure(item, x, y)
  File "C:\Users\Cr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 5956, in relocate_figure
    self._TKCanvas2.move(figure, shift_converted[0] - xy[0], shift_converted[1] - xy[1])
IndexError: list index out of range
